blog/urls.py
from django.urls import path
from blog import views
app_name = 'blog'


urlpatterns = [
    path('', views.index, name='bolg_index'),
    path('<int:blog_id>', views.detail, name='blog_detail'),
    path('category/<int:category_id>', views.category, name='blog_category'),
    path('tag/<int:tag_id>', views.tags, name='blog_tags'),
    path('search/', views.search, name='blog_search'),
    path('sarchives/<year>/<month>', views.archives, name='blog_archives'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views as blog_views
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Entry

info_dict = {
    'queryset': Entry.objects.all(),
    'date_field': 'modified_time'
}


urlpatterns = [
    path('',blog_views.index),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap,{'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = blog_views.permission_denied
handler404 = blog_views.page_not_found
handler500 = blog_views.server_error

blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='博客分类')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客分类 '
        verbose_name_plural = '博客分类'


class Tag(models.Model):
    name = models.CharField(max_length=128, verbose_name='博客标签')

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "博客标签"
        verbose_name_plural = "博客标签"


class Entry(models.Model):
    title = models.CharField(max_length=128, verbose_name="文章标题")
    author = models.ForeignKey(User, verbose_name="博客作者", on_delete=models.CASCADE)
    img = models.ImageField(upload_to='blog_images', null=True, blank=True)
    body = models.TextField(verbose_name="博客正文")
    abstract = models.TextField(max_length=256, blank=True, null=True, verbose_name="博客摘要")
    visiting = models.PositiveIntegerField(default=0, verbose_name="博客访问量")
    category = models.ManyToManyField('Category', verbose_name="博客分类")
    tags = models.ManyToManyField('Tag', verbose_name="博客标签")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    modified_time = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_detail', kwargs={'blog_id': self.id})

    def increase_visiting(self):
        self.visiting += 1
        self.save(update_fields=['visiting'])

    class Meta:
        ordering = ['-created_time']
        verbose_name = "博客"
        verbose_name_plural = "博客"

blog/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from . import models
import markdown
import pygments
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def make_paginator(objects, page, num=10):
    paginator = Paginator(objects, num)
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)
    return object_list, paginator


def pagination_data(paginator, page):
    if paginator.num_pages == 1:
        return {}
    left = []
    right = []
    left_has_more = False
    right_has_more = False
    first = False
    last = False
    try:
        page_number = int(page)
    except ValueError:
        page_number = 1
    except:
        page_number = 1
    total_pages = paginator.num_pages
    page_range = paginator.page_range
    if page_number == 1:
        right = page_range[page_number:page_number+4]
        if right[-1] < total_pages - 1:
            right_has_more = True
        if right[-1] < total_pages:
            last = True

    elif page_number == total_pages:
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
        if left[0] > 2:
            left_has_more = True
        if left[0] > 1:
            first = True

    else:
        left = page_range[(page_number-3) if (page_number - 3) > 0 else 0:page_number-1]
        right = page_range[page_number:page_number+2]

        if right[-1] < total_pages - 1:
            right_has_more = True
        if right[-1] < total_pages:
            last = True
        if left[0] > 2:
            left_has_more = True
        if left[0] > 1:
            first = True
    data = {
        'left': left,
        'right':right,
        'left_has_more':left_has_more,
        'right_has_more':right_has_more,
        'first':first,
        'last':last,
    }
    return data


def index(request):
    entries = models.Entry.objects.all()
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())


def detail(request, blog_id):
    # entry = models.Entry.objects.get(id=blog_id)
    # 如果id存在就返回正确页面，否则返回404页面
    entry = get_object_or_404(models.Entry, id=blog_id)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    entry.body = md.convert(entry.body)
    entry.toc =md.toc
    entry.increase_visiting()
    return render(request, 'blog/detail.html', locals())


def category(request, category_id):
    categy = get_object_or_404(models.Category, id=category_id)
    # categy = models.Category.objects.get(id=category_id)
    entries = models.Entry.objects.filter(category=categy)
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())


def tags(request, tag_id):
    tag = get_object_or_404(models.Tag, id=tag_id)
    # tag =models.Tag.objects.get(id=tag_id)
    if tag.name == '全部':
        entries = models.Entry.objects.all()
    else:
        entries = models.Entry.objects.filter(tags=tag)
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())


def search(request):
    keyword = request.GET.get('keyword',None)
    if not keyword:
        error_msg = "请输入关键字"
        return render(request, 'blog/index.html', locals())

    entries = models.Entry.objects.filter(Q(title__icontains=keyword) | Q(body__icontains=keyword))
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())


def archives(request, year, month):
    entries = models.Entry.objects.filter(created_time__year=year, created_time__month=month)
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())


def permission_denied(request, exception, template_name='blog/403.html'):
    return render(request, template_name, locals())


def page_not_found(request, exception, template_name='blog/404.html'):
    return render(request, template_name, locals())


def server_error(exception):
    return render("blog/500.html", status=500)

blog/templates/blog/base.html
<!doctype html>
{% load staticfiles %}
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}基本模板{%  endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'bootstrap-3.4.1-dist/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'blog/css/blog_nav.css' %}" >
    {% block css %}
    {%  endblock %}
    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

      <nav class="navbar navbar-fixed-top">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="{% static 'blog/images/logo.jpg' %}"></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/blog/">博客</a></li>
              <li><a href="#">关于博主</a></li>
              <li><a href="#">联系我们</a></li>
            </ul>
            <form class="navbar-form navbar-left" action="{% url 'blog:blog_search' %}" method="get">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search" name="keyword">
              </div>
              <button type="submit" class="btn btn-default">搜索</button>
            </form>
{#            <ul class="nav navbar-nav navbar-right">#}
{#              <li><a href="#">登录</a></li>#}
{#            </ul>#}
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

    {% block content %}

    {% endblock %}

    <div id="back-to-top">
        <i class="glyphicon glyphicon-arrow-up"></i>
    </div>

    <footer>
        <div class="footer" role="navigation">
            <div class="container">
                <div class="navbar-text">
                    <ul class="footer-text">
                       <li><a href="#">主页</a></li>
                       <li><a href="#" target="_blank">联系我们</a></li>
                       <li><a href="#">关于博主</a></li>
                       <li><a href="#" target="_blank">文档支持</a></li>
                       <li><a href="/blog" target="_blank">博客首页</a></li>


                    </ul>
                    <p>Copyright © 2021  yyq的博客</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="{% static 'jquery.min.js' %}" ></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="{% static 'bootstrap-3.4.1-dist/js/bootstrap.min.js' %}" ></script>
      <script>
          $("#back-to-top").click(function () {
              window.scrollTo(0, 0);
          });
      </script>
    {% block script %}
    {%  endblock %}
  </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}博客详细页面{% endblock%}
{% block css %}
    <link href="{% static 'blog/css/github.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3>{{ entry.title }}</h3>
                <p>
                    <strong>{{ entry.author }}</strong>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    {{ entry.created_time|date:'Y年m月d日' }}
                    &nbsp;&nbsp;&nbsp;&nbsp;分类：
                    {% for category in entry.category.all %}
                        <a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                    {% endfor %}
                    &nbsp;&nbsp;&nbsp;&nbsp;标签：
                    {% for tag in entry.tags.all %}
                        <a href="{% url 'blog:blog_tags' tag.id %}">{{ tag.name }}</a>
                    {% endfor %}
                `   &nbsp;&nbsp;&nbsp;&nbsp;浏览量：
                    {{ entry.visiting }}

                </p>
                {% if entry.img %}
                    <img src="{{ entry.img.url }}" alt="博客配图" width="25%">
                {% endif %}
                <p>
                    {{ entry.body|safe }}
                </p>
            </div>
        <div class="col-md-1">
        </div>
        <div class="col-md-3">
            {% block toc %}
                <div class="row">
                    <div class="widget">
                        <h3>目录：</h3><hr />
                         {{ entry.toc | safe }}
                    </div>
                </div>
            {% endblock %}
            {% include 'blog/right_side_bar.html' %}
        </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}博客首页{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                {% for entry in entry_list %}
                    <br>
                <h4><a href="{{entry.get_absolute_url}}">{{entry.title}}</a></h4>
{#                    {% if entry.img %}#}
{#                         <img src="{{ entry.img.url }}" alt="博客配图" width="25%">#}
{#                    {% endif %}#}
{##}
{#                    {% if entry.abstract %}#}
{#                        <p>{{ entry.abstract }}</p>#}
{#                    {% else %}#}
{#                        <p>{{ entry.body|truncatechars:128 }}</p>#}
{#                    {% endif %}#}
                    <p>
                        <span>作者：{{ entry.author }}</span>
                        <span>&nbsp;&nbsp;&nbsp;&nbsp;发表时间：{{ entry.created_time }}</span>
                        <span>&nbsp;&nbsp;&nbsp;&nbsp;浏览量：{{ entry.visiting }}</span>
                    </p>
                {% endfor %}
                <hr/>

                <div id="paginator" class="pull-left">
                    <ul class="pagination pagination-lg">
                        {% if entry_list.has_previous %}
                            <li><a href="?page={{ entry_list.previous_page_number }}"><i class="glyphicon glyphicon-chevron-left"></i>前一页</a></li>
                        {% endif %}

                        {% if first %}
                            <li><a href="?page=1">1</a></li>
                        {% endif %}

                        {% if left %}
                            {% if left_has_more %}
                                <span>···</span>
                            {% endif %}

                            {% for i in left %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                        {% endif %}

                        <li class="active"><a href="?page={{ entry_list.number }}">{{ entry_list.number }}</a></li>

                        {% if right %}
                            {% for i in right %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}

                            {% if right_has_more %}
                                <span>···</span>
                            {% endif %}
                            {% if left_has_more %}
                                <span>···</span>
                            {% endif %}
                        {% endif %}

                        {% if last %}
                            <li><a href="?page={{ entry_list.num_page }}">{{ entry_list.num_page }}</a></li>
                        {% endif %}

                        {% if entry_list.has_next %}
                            <li><a href="?page={{ entry_list.next_page_number }}">下一页<i class="glyphicon glyphicon-chevron-right"></i></a></li>
                        {% endif %}
                    </ul>

                </div>
            </div>

        <div class="col-md-3">
            {% include 'blog/right_side_bar.html' %}
        </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/right_side_bar.html
{% load blog_tags %}
{#    {% block toc %}{% endblock %}#}
    <div class="row">
        <div class="widget">
            <h3>最新博客：</h3><hr />
            {% get_recent_entries as recent_entry_list %}
            {% for entry in recent_entry_list %}
                <div>
                    <a href="{{ entry.get_absolute_url }}" title="{{ entry.title }}">
                        {% if entry.title|length > 16  %}
                            {{ entry.title | truncatechars:16 }}...
                        {% else %}
                            {{ entry.title }}
                        {% endif %}
                    </a>
                    <div>
                        {{ entry.author }} 发表于： {{ entry.created_time|date:'Y年m月d日' }}
                    </div>
                    <br>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="row">
        <div class="widget">
            <h3>推荐博客：</h3><hr />
            {% get_popular_entries as popular_entry_list %}
            {% for entry in popular_entry_list %}
                <div >
                    <a href="{{ entry.get_absolute_url }}" title="{{ entry.title }}">
                        {% if entry.title|length > 16  %}
                            {{ entry.title | truncatechars:16 }}...
                        {% else %}
                            {{ entry.title }}
                        {% endif %}
                    </a>
                    &nbsp;
                    <span class="badge">{{ entry.visiting }}</span>
                    <div>
                        {{ entry.author }} 发表于： {{ entry.created_time|date:'Y年m月d日' }}
                    </div>
                    <br>
                </div>
            {% endfor %}
        </div>
    </div>


    <div class="row">
        <div class="widget">
            <h3>分类：</h3><hr />
            {% get_categories as category_list %}
                <ul class="list-group">
                    {% for category in category_list %}
                        <li class="list-group-item">
                            <a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                            <span class="badge">{% get_entry_count_of_category category.name %}</span>
                        </li>
                    {% endfor %}
                </ul>
        </div>
    </div>

    <div class="row">
        <div class="widget">
            <h3>归档：</h3><hr />
            {% archives as date_list %}
            <ul class="list-group">
                {% for date in date_list %}
                    <li class="list-group-item">
                        <a href="{% url 'blog:blog_archives' date.year date.month %}">
                            {{ date.year }} 年 {{ date.month }} 月
                        </a>
                        <span class="badge">{% get_entry_count_of_date date.year date.month %}</span>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="widget">
            <h3>标签云：</h3><hr />
            {% get_tags as tag_list %}
            {% for tag in tag_list %}
                <a href="{% url 'blog:blog_tags' tag.id %}">
                    <span class="label {% cycle 'label-default' 'label-primary' 'label-success' 'label-info' 'label-warning' 'label-danger' %}">{{ tag.name }}</span>
                </a>
            {% endfor %}

        </div>
    </div><br>